export const ACTION_TYPES = {
  GLOBAL_LOCATION_CHANGE: "@@router/LOCATION_CHANGE",

  SIGN_LIST_CHANGE_SEARCH_INPUT: Symbol("SIGN_LIST.CHANGE_SEARCH_INPUT"),

  SIGN_BOX_REACH_BOX_MOVING_HEIGHT: Symbol("SIGN_BOX.REACH_BOX_MOVING_HEIGHT"),
  SIGN_BOX_LEAVE_BOX_MOVING_HEIGHT: Symbol("SIGN_BOX.LEAVE_BOX_MOVING_HEIGHT"),

  HEADER_REACH_SCROLL_TOP: Symbol("HEADER.REACH_SCROLL_TOP"),
  HEADER_LEAVE_SCROLL_TOP: Symbol("HEADER.LEAVE_SCROLL_TOP"),

  SIGN_BOX_CHANGE_NAME_INPUT: Symbol("SIGN_BOX.CHANGE_NAME_INPUT"),
  SIGN_BOX_CHANGE_AFFILIATION: Symbol("SIGN_BOX.CHANGE_AFFILIATION"),
  SIGN_BOX_CHANGE_AFFILIATION_EMAIL: Symbol("SIGN_BOX.CHANGE_AFFILIATION_EMAIL"),
  SIGN_BOX_CHANGE_COMMENT: Symbol("SIGN_BOX.CHANGE_COMMENT"),
};
